{
    'name': 'Music School',
    'version': '18.0.0.0',
    'description': 'Manages a music school with students, teachers and classes',
    'summary': 'Manages a music school with students, teachers and classes',
    'author': 'Idris Kalouache',
    'website': '',
    'license': 'LGPL-3',
    'category': 'Music School',
    'images': ['static/img/logo.png'],
    'depends': [
        'base'
    ],
    'data':[
        'data/music_school_data.xml',
        'data/ir_cron.xml',
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'views/music_school_student_views.xml',
        'views/music_school_instrument_views.xml',
        'views/music_school_teacher_views.xml',
        'views/music_school_course_views.xml',
        'views/music_school_classroom_views.xml',
        'views/music_school_lecture_views.xml',
        'views/music_school_lecture_attendance_views.xml',
        'views/music_school_exam_views.xml',
        'views/music_school_menuitems.xml',
        'wizard/music_school_course_change_state.xml',
        'wizard/music_school_lecture_batch.xml',
        'report/music_school_course_report.xml',
        'report/music_school_course_simple_report.xml',
        'report/music_school_lecture_report.xml',
        'report/music_school_exam_results_report.xml',
    ],
}